### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by Niminem** [elliotwaite/nim-opengl-tutorials-by-the-cherno#1]
@elliotwaite 

Just wanted to say thanks for doing this! I'm just getting started in graphics programming with Nim, this helps a lot <#

**Comment by elliotwaite** [comment]
Awesome. I wasn't sure if anyone was going to find this repo helpful, but I'm glad to hear you did. Thanks for leaving this comment.

**Comment by elliotwaite** [comment]
I'm going to close this issue so that I don't mistake it for an issue that I need to fix, but thanks again for the kind comment.
